<Type Name="TargetInvocationException" FullName="System.Reflection.TargetInvocationException">
  <Metadata><Meta Name="ms.openlocfilehash" Value="cccdf1fda64610ab095fba0c38390b42e658f341" /><Meta Name="ms.sourcegitcommit" Value="a3e01ec36374fac54a55add0dcc1e754e394abeb" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="es-ES" /><Meta Name="ms.lasthandoff" Value="03/30/2019" /><Meta Name="ms.locfileid" Value="58703815" /></Metadata><TypeSignature Language="C#" Value="public sealed class TargetInvocationException : ApplicationException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit TargetInvocationException extends System.ApplicationException" />
  <TypeSignature Language="DocId" Value="T:System.Reflection.TargetInvocationException" />
  <TypeSignature Language="VB.NET" Value="Public NotInheritable Class TargetInvocationException&#xA;Inherits ApplicationException" />
  <TypeSignature Language="C++ CLI" Value="public ref class TargetInvocationException sealed : ApplicationException" />
  <TypeSignature Language="F#" Value="type TargetInvocationException = class&#xA;    inherit ApplicationException" />
  <AssemblyInfo>
    <AssemblyName>System.Reflection</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.10.0</AssemblyVersion>
    <AssemblyVersion>4.1.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>1.0.5000.0</AssemblyVersion>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
    <BaseTypeName FrameworkAlternate="netframework-4.5">System.ApplicationException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
      <AttributeName>System.Runtime.InteropServices.ComVisible(true)</AttributeName>
    </Attribute>
    <Attribute FrameworkAlternate="netframework-1.1;netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netframework-4.8;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0">
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary><span data-ttu-id="fdbb0-101">Excepción que se produce en los métodos llamados mediante reflexión.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-101">The exception that is thrown by methods invoked through reflection.</span></span> <span data-ttu-id="fdbb0-102">Esta clase no puede heredarse.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-102">This class cannot be inherited.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="fdbb0-103">Para obtener más información, vea <xref:System.Reflection.MethodBase.Invoke%2A>.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-103">For more information, see <xref:System.Reflection.MethodBase.Invoke%2A>.</span></span>  
  
 <span data-ttu-id="fdbb0-104">`TargetInvocationException` usa el COR_E_TARGETINVOCATION HRESULT que tiene el valor 0 x 80131604.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-104">`TargetInvocationException` uses the HRESULT COR_E_TARGETINVOCATION which has the value 0x80131604.</span></span>  
  
 <span data-ttu-id="fdbb0-105">Cuando crea, el `TargetInvocationException` se pasa una referencia a la excepción producida por el método invocado mediante reflexión.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-105">When created, the `TargetInvocationException` is passed a reference to the exception thrown by the method invoked through reflection.</span></span> <span data-ttu-id="fdbb0-106">El <xref:System.Exception.InnerException%2A> propiedad contiene la excepción subyacente.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-106">The <xref:System.Exception.InnerException%2A> property holds the underlying exception.</span></span>  
  
 ]]></format>
    </remarks>
    <altmember cref="P:System.Exception.InnerException" />
    <altmember cref="T:System.Exception" />
    <related type="Article" href="~/docs/standard/exceptions/index.md"><span data-ttu-id="fdbb0-107">Controlar y generar excepciones en .NET</span><span class="sxs-lookup"><span data-stu-id="fdbb0-107">Handling and throwing exceptions in .NET</span></span></related>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Reflection</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary><span data-ttu-id="fdbb0-108">Inicializa una nueva instancia de la clase <see cref="T:System.Reflection.TargetInvocationException" />.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-108">Initializes a new instance of the <see cref="T:System.Reflection.TargetInvocationException" /> class.</span></span></summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public TargetInvocationException (Exception inner);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception inner) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Reflection.TargetInvocationException.#ctor(System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (inner As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; TargetInvocationException(Exception ^ inner);" />
      <MemberSignature Language="F#" Value="new System.Reflection.TargetInvocationException : Exception -&gt; System.Reflection.TargetInvocationException" Usage="new System.Reflection.TargetInvocationException inner" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Reflection</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="inner" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="inner"><span data-ttu-id="fdbb0-109">Excepción que es la causa de la excepción actual.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-109">The exception that is the cause of the current exception.</span></span> <span data-ttu-id="fdbb0-110">Si el parámetro <paramref name="inner" /> no es <see langword="null" />, la excepción actual se produce en un bloque <see langword="catch" /> que controla la excepción interna.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-110">If the <paramref name="inner" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span></span></param>
        <summary><span data-ttu-id="fdbb0-111">Inicializa una nueva instancia de la clase <see cref="T:System.Reflection.TargetInvocationException" /> con una referencia a la excepción interna que representa la causa de esta excepción.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-111">Initializes a new instance of the <see cref="T:System.Reflection.TargetInvocationException" /> class with a reference to the inner exception that is the cause of this exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="fdbb0-112">Una excepción que se produce como consecuencia directa de una excepción anterior debe incluir una referencia a esta última en la propiedad <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-112">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="fdbb0-113">La propiedad <xref:System.Exception.InnerException%2A> devuelve el mismo valor que se haya pasado al constructor, o bien `null` en caso de que la propiedad <xref:System.Exception.InnerException%2A> no le haya proporcionado al constructor el valor de la excepción interna.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-113">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="fdbb0-114">En la tabla siguiente se muestran los valores de propiedad iniciales para una instancia de <xref:System.Reflection.TargetInvocationException>.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-114">The following table shows the initial property values for an instance of <xref:System.Reflection.TargetInvocationException>.</span></span>  
  
|<span data-ttu-id="fdbb0-115">Propiedad.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-115">Property</span></span>|<span data-ttu-id="fdbb0-116">Valor</span><span class="sxs-lookup"><span data-stu-id="fdbb0-116">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="fdbb0-117">Referencia a la excepción interna.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-117">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="fdbb0-118">Cadena con el mensaje de error.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-118">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
        <related type="Article" href="~/docs/standard/exceptions/index.md"><span data-ttu-id="fdbb0-119">Controlar y generar excepciones en .NET</span><span class="sxs-lookup"><span data-stu-id="fdbb0-119">Handling and throwing exceptions in .NET</span></span></related>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public TargetInvocationException (string message, Exception inner);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception inner) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Reflection.TargetInvocationException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, inner As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; TargetInvocationException(System::String ^ message, Exception ^ inner);" />
      <MemberSignature Language="F#" Value="new System.Reflection.TargetInvocationException : string * Exception -&gt; System.Reflection.TargetInvocationException" Usage="new System.Reflection.TargetInvocationException (message, inner)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Reflection</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="inner" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="fdbb0-120">Mensaje de error que explica el motivo de la excepción.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-120">The error message that explains the reason for the exception.</span></span></param>
        <param name="inner"><span data-ttu-id="fdbb0-121">Excepción que es la causa de la excepción actual.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-121">The exception that is the cause of the current exception.</span></span> <span data-ttu-id="fdbb0-122">Si el parámetro <paramref name="inner" /> no es <see langword="null" />, la excepción actual se produce en un bloque <see langword="catch" /> que controla la excepción interna.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-122">If the <paramref name="inner" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span></span></param>
        <summary><span data-ttu-id="fdbb0-123">Inicializa una nueva instancia de la clase <see cref="T:System.Reflection.TargetInvocationException" /> con el mensaje de error especificado y una referencia a la excepción interna que representa la causa de esta excepción.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-123">Initializes a new instance of the <see cref="T:System.Reflection.TargetInvocationException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="fdbb0-124">Una excepción que se produce como consecuencia directa de una excepción anterior debe incluir una referencia a esta última en la propiedad <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-124">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="fdbb0-125">La propiedad <xref:System.Exception.InnerException%2A> devuelve el mismo valor que se haya pasado al constructor, o bien `null` en caso de que la propiedad <xref:System.Exception.InnerException%2A> no le haya proporcionado al constructor el valor de la excepción interna.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-125">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="fdbb0-126">En la tabla siguiente se muestran los valores de propiedad iniciales para una instancia de <xref:System.Reflection.TargetInvocationException>.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-126">The following table shows the initial property values for an instance of <xref:System.Reflection.TargetInvocationException>.</span></span>  
  
|<span data-ttu-id="fdbb0-127">Propiedad.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-127">Property</span></span>|<span data-ttu-id="fdbb0-128">Valor</span><span class="sxs-lookup"><span data-stu-id="fdbb0-128">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="fdbb0-129">Referencia a la excepción interna.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-129">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="fdbb0-130">Cadena con el mensaje de error.</span><span class="sxs-lookup"><span data-stu-id="fdbb0-130">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
        <related type="Article" href="~/docs/standard/exceptions/index.md"><span data-ttu-id="fdbb0-131">Controlar y generar excepciones en .NET</span><span class="sxs-lookup"><span data-stu-id="fdbb0-131">Handling and throwing exceptions in .NET</span></span></related>
      </Docs>
    </Member>
  </Members>
</Type>